"""Add passenger table

Revision ID: 1a62613ce175
Revises: 2eeb15ecfe3e
Create Date: 2013-06-08 18:29:57.060190

"""

# revision identifiers, used by Alembic.
revision = '1a62613ce175'
down_revision = '2eeb15ecfe3e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
