"""Add car_make, car_model and car_color to Driver model

Revision ID: 1a99e35d8c6e
Revises: 649d910c29e
Create Date: 2014-08-01 13:54:26.518189

"""

# revision identifiers, used by Alembic.
revision = '1a99e35d8c6e'
down_revision = '649d910c29e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver', sa.Column('car_model', sa.String(), nullable=True))
    op.add_column('driver', sa.Column('car_make', sa.String(), nullable=True))
    op.add_column('driver', sa.Column('car_color', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver', 'car_color')
    op.drop_column('driver', 'car_make')
    op.drop_column('driver', 'car_model')
    ### end Alembic commands ###
