"""add avatar_unresolved

Revision ID: 1c47b16ffb16
Revises: 26a0446f93b6
Create Date: 2014-12-29 18:32:54.210851

"""

# revision identifiers, used by Alembic.
revision = '1c47b16ffb16'
down_revision = '26a0446f93b6'

import sqlalchemy as sa
import requests
from alembic import op


def location_redirect(url):
    r = requests.get(url, allow_redirects=False)
    return r.headers['Location']


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_unresolved', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_unresolved')
    ### end Alembic commands ###
