"""promo code tables

Revision ID: 1ecc1e5ab38e
Revises: 5666aa92764c
Create Date: 2015-02-02 21:55:40.618033

"""

# revision identifiers, used by Alembic.
revision = '1ecc1e5ab38e'
down_revision = '5666aa92764c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_code',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('eligible_till', sa.DateTime(), nullable=False),
    sa.Column('active_for', sa.Integer(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_promo_code',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('promo_code_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_code.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    #op.create_foreign_key(None, 'payment', 'promo_code', ['promo_code_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_promo_code')
    op.drop_table('promo_code')
    ### end Alembic commands ###
