"""add pickup_time

Revision ID: 1fd451906279
Revises: 26a0446f93b6
Create Date: 2015-01-06 10:54:29.190817

"""

# revision identifiers, used by Alembic.
revision = '1fd451906279'
down_revision = '26a0446f93b6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passenger', sa.Column('pickup_time', sa.Time(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('passenger', 'pickup_time')
    ### end Alembic commands ###
