"""Add passenger table

Revision ID: 1fd5719f9e58
Revises: 2eeb15ecfe3e
Create Date: 2013-06-08 18:58:09.028371

"""

# revision identifiers, used by Alembic.
revision = '1fd5719f9e58'
down_revision = '2eeb15ecfe3e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passenger',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('origin', sa.Text(), nullable=True),
    sa.Column('destination', sa.Text(), nullable=True),
    sa.Column('buddies', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passenger')
    ### end Alembic commands ###
