"""Add facebook_id column to user

Revision ID: 2699e1b1f892
Revises: 1fdf538ffc93
Create Date: 2014-07-22 21:53:02.351385

"""

# revision identifiers, used by Alembic.
revision = '2699e1b1f892'
down_revision = '1fdf538ffc93'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('facebook_id', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'facebook_id')
    ### end Alembic commands ###
