"""add first and last names

Revision ID: 26a0446f93b6
Revises: 2ddc64c7e5d4
Create Date: 2014-12-17 22:22:25.608366

"""

# revision identifiers, used by Alembic.
revision = '26a0446f93b6'
down_revision = '2ddc64c7e5d4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(), server_default='', nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(), server_default='', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    ### end Alembic commands ###
