"""Create PRESSKIT2015 promo code

Revision ID: 287a6689b026
Revises: 1030ec6cfb61
Create Date: 2015-05-17 18:05:38.161025

"""

# revision identifiers, used by Alembic.
revision = '287a6689b026'
down_revision = '1030ec6cfb61'

from datetime import timedelta
from datetime import datetime as dt

from strappon.repositories.promo_codes import PromoCodesRepository
from weblib.db import create_session


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    ### end Alembic commands ###
    eligible_till = dt.utcnow() + timedelta(days=7)
    orm = create_session()
    presskit2015 = PromoCodesRepository.add(name='PRESSKIT2015',
                                            eligible_till=eligible_till,
                                            active_for=30,
                                            credits=5)
    orm.add(presskit2015)
    orm.commit()


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    ### end Alembic commands ###
    pass
