"""add payments table

Revision ID: 28d5a7cc2f71
Revises: 314a5430c818
Create Date: 2014-10-05 13:46:15.272052

"""

# revision identifiers, used by Alembic.
revision = '28d5a7cc2f71'
down_revision = '314a5430c818'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('drive_request_id', sa.String(), nullable=True),
    sa.Column('payer_user_id', sa.String(), nullable=True),
    sa.Column('payee_user_id', sa.String(), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drive_request_id'], ['drive_request.id'], ),
    sa.ForeignKeyConstraint(['payee_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['payer_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    ### end Alembic commands ###
