"""marco polo promo

Revision ID: 30edc10d4ef3
Revises: 1ecc1e5ab38e
Create Date: 2015-02-02 22:07:02.429298

"""

# revision identifiers, used by Alembic.
revision = '30edc10d4ef3'
down_revision = '1ecc1e5ab38e'

from datetime import timedelta
from datetime import datetime as dt

from strappon.repositories.promo_codes import PromoCodesRepository
from weblib.db import create_session


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    ### end Alembic commands ###
    eligible_till = dt.utcnow() + timedelta(days=16)
    orm = create_session()
    marco_polo = PromoCodesRepository.add(name='WELOVERIONI',
                                          eligible_till=eligible_till,
                                          active_for=30,
                                          credits=10)
    orm.add(marco_polo)
    orm.commit()


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    ### end Alembic commands ###
    pass
