"""add facebook_token to user

Revision ID: 365eade5794
Revises: 38190f6b986e
Create Date: 2015-04-11 12:23:50.629723

"""

# revision identifiers, used by Alembic.
revision = '365eade5794'
down_revision = '38190f6b986e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('facebook_token', sa.String(), server_default='', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'facebook_token')
    ### end Alembic commands ###
