"""Add car_type column to driver

Revision ID: 368aad29e32e
Revises: 649d910c29e
Create Date: 2014-07-31 23:05:36.512597

"""

# revision identifiers, used by Alembic.
revision = '368aad29e32e'
down_revision = '649d910c29e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver', sa.Column('car_type', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver', 'car_type')
    ### end Alembic commands ###
