"""Add user table

Revision ID: 3744e5c447f3
Revises: 49955cbe6123
Create Date: 2013-06-01 13:04:09.066908

"""

# revision identifiers, used by Alembic.
revision = '3744e5c447f3'
down_revision = '49955cbe6123'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
