"""add eggpartyoff promo code

Revision ID: 38190f6b986e
Revises: 38836b61b46c
Create Date: 2015-03-28 15:36:55.201497

"""

# revision identifiers, used by Alembic.
revision = '38190f6b986e'
down_revision = '38836b61b46c'

from datetime import timedelta
from datetime import datetime as dt

from strappon.repositories.promo_codes import PromoCodesRepository
from weblib.db import create_session


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    ### end Alembic commands ###
    eligible_till = dt.utcnow() + timedelta(days=7)
    orm = create_session()
    marco_polo = PromoCodesRepository.add(name='EGGOFF',
                                          eligible_till=eligible_till,
                                          active_for=30,
                                          credits=5)
    orm.add(marco_polo)
    orm.commit()


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    ### end Alembic commands ###
    pass
