"""new user promo

Revision ID: 38836b61b46c
Revises: 30edc10d4ef3
Create Date: 2015-02-10 22:28:04.800238

"""

# revision identifiers, used by Alembic.
revision = '38836b61b46c'
down_revision = '30edc10d4ef3'

import sqlalchemy as sa
from datetime import datetime as dt
from datetime import timedelta
from alembic import op
from strappon.models import Base
from strappon.models import User
from strappon.repositories.payments import PaymentsRepository
from strappon.repositories.promo_codes import PromoCodesRepository
from weblib.db import create_session


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    ### end Alembic commands ###
    eligible_till = dt.utcnow() + timedelta(days=3650)
    orm = create_session()
    promo = PromoCodesRepository.add(name=PromoCodesRepository.NEW_USER,
                                     eligible_till=eligible_till,
                                     active_for=60,
                                     credits=10)
    orm.add(promo)
    for u in Base.session.query(User.id):
        orm.add(PromoCodesRepository.activate_promo_code(u[0],
                                                         promo.id))
        orm.add(PaymentsRepository.add(None,
                                       None,
                                       u[0],
                                       0,
                                       promo.credits,
                                       promo.id))
    orm.commit()


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    ### end Alembic commands ###
    pass
