"""Remove sessions table

Revision ID: 40d8e159f752
Revises: 1a99e35d8c6e
Create Date: 2014-09-30 20:22:57.017420

"""

# revision identifiers, used by Alembic.
revision = '40d8e159f752'
down_revision = '1a99e35d8c6e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'session')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'session',
    sa.Column(u'session_id', sa.VARCHAR(), nullable=False),
    sa.Column(u'atime', sa.TIME(), nullable=True),
    sa.Column(u'data', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint(u'session_id')
    )
    ### end Alembic commands ###
