"""Add session table

Revision ID: 49955cbe6123
Revises: None
Create Date: 2013-06-01 10:39:35.109952

"""

# revision identifiers, used by Alembic.
revision = '49955cbe6123'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('atime', sa.Time(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session')
    ### end Alembic commands ###
