"""Add distance to passenger

Revision ID: 4ddf082083cd
Revises: 40d8e159f752
Create Date: 2014-09-30 21:21:03.513264

"""

# revision identifiers, used by Alembic.
revision = '4ddf082083cd'
down_revision = '40d8e159f752'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passenger', sa.Column('distance', sa.Float(), server_default='0.0', nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('passenger', 'distance')
    ### end Alembic commands ###
