"""Add distance to passenger

Revision ID: 4ddf082083cd
Revises: 40d8e159f752
Create Date: 2014-09-30 21:21:03.513264

"""

# revision identifiers, used by Alembic.
revision = '4ddf082083cd'
down_revision = '40d8e159f752'

from alembic import op
import sqlalchemy as sa

from app.models import Passenger
from app.pubsub import distance
from app.weblib.db import expunged
from app.weblib.db import create_session


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passenger', sa.Column('distance', sa.Float(), nullable=True))
    ### end Alembic commands ###
    orm = create_session()
    for p in Passenger.query:
        p = expunged(p, Passenger.session)
        p.distance = distance(p.origin_latitude, p.origin_longitude,
                              p.destination_latitude, p.destination_longitude)
        orm.add(p)
    orm.commit()


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('passenger', 'distance')
    ### end Alembic commands ###
