"""add rate table

Revision ID: 590e1eac4168
Revises: 2f6c56f0af54
Create Date: 2014-07-09 00:40:48.095571

"""

# revision identifiers, used by Alembic.
revision = '590e1eac4168'
down_revision = '2f6c56f0af54'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rater_user_id', sa.String(), nullable=True),
    sa.Column('rated_user_id', sa.String(), nullable=True),
    sa.Column('stars', sa.Float(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rated_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['rater_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rate')
    ### end Alembic commands ###
